config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  target: postgres
    
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: postgres
      pass: password
      port: 5432
      dbname: postgres
      schema: integration_tests
      threads: 1
    actions-postgres:
      type: postgres
      host: postgres
      user: postgres
      pass: password
      port: 5432
      dbname: postgres
      schema: integration_tests
      threads: 1

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_TEST_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE') }}"
      schema: integration_tests
      threads: 4
